#!/usr/bin/env perl

use strict;
use warnings;
use JIRA::REST;
use JSON;
use Net::Netrc;
use YAML;
use Data::Dumper;

die "Usage: jira-get-issue ISSUE\n" unless @ARGV;

my $wanted = shift; # DOC-1123

my $server      = $ENV{ATLASSIAN_SERVER};
my $credentials = Net::Netrc->lookup($server);
my $username    = $credentials->login;
my $password    = $credentials->password;

my $jira = JIRA::REST->new( $server, $username, $password );

my $issue = $jira->GET( "/issue/$wanted" );

print Dump $issue;
