#!/usr/bin/env perl

use strict;
use warnings;
use JIRA::REST;
use Net::Netrc;
use File::Slurp qw< slurp >;
use Data::Dumper;

die "Usage: jira-create-issue PROJECT SUMMARY\n" unless @ARGV == 2;

my ($project, $summary) = @ARGV; # DOC "Can't understand this page"
my $DEBUG = 0;
print "PROJECT: $project\nSUMMARY: $summary\n" if $DEBUG;

my $server      = $ENV{ATLASSIAN_SERVER};
my $credentials = Net::Netrc->lookup($server);
my $username    = $credentials->login;
my $password    = $credentials->password;

# Pop open a temp file in $EDITOR for the description.

my $tmpdir = $ENV{TMPDIR};
my $tmpfile = "jira-create-issue-$project-$$.txt";
my $tmp_path = $tmpdir . $tmpfile;

my $editor = $ENV{EDITOR};
if ( -t STDIN ) {
    system qq{$editor $tmp_path}
      or print STDERR "Couldn't open '$editor $tmp_path': $!\n";
}
else {
    exec qq{$editor < /dev/tty $tmp_path}
      or print STDERR "Couldn't exec '$editor $tmp_path': $!\n";
}

# error check result of editor call here?
my $description = slurp $tmp_path;

print "DESCRIPTION: $description\n" if $DEBUG;

my $jira = JIRA::REST->new( $server, $username, $password );

my $issue = $jira->POST( "/issue", undef,
			 {
			  fields => {
				     project => { key => "$project" }, # DOC or PF, likely
				     issuetype => { name => "Task" }, # id => 3
				     summary => "$summary",
				     description => "$description",
				     assignee => { name => "$username" },
				    },
			 }
		       );

print Dumper $issue;
