#!/usr/bin/env perl

use strict;
use warnings;
use autodie;
use JIRA::REST;
use File::Slurp qw< slurp >;
use Net::Netrc;

my $err_text = <<"EOF";
Usage: jira-set-issue-status ISSUE STATUS_ID

Try one of these:

| STATUS_ID | Meaning             |
|-----------+---------------------|
|        11 | 'Start Progress'    |
|       141 | 'Start Code Review' |
|       161 | 'Blocked'           |
|       111 | 'Close'             |
|       191 | 'Testing'           |
|       261 | 'Resolve'           |
EOF

die $err_text unless @ARGV == 2;

my ($wanted, $status) = @ARGV;

my $server      = $ENV{ATLASSIAN_SERVER};
my $credentials = Net::Netrc->lookup($server);
my $username    = $credentials->login;
my $password    = $credentials->password;

my $jira = JIRA::REST->new( $server, $username, $password );

my $payload = { transition => { id => $status } };

# PATH, QUERY, VALUE, [ HEADERS ]
my $issue = $jira->POST( "/issue/$wanted/transitions", undef, $payload );
